/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/250725-SmallStationLaunched': RouteRecordInfo<
      '/posts/250725-SmallStationLaunched',
      '/posts/250725-SmallStationLaunched',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/250726-ESP8266NetworkSetup': RouteRecordInfo<
      '/posts/250726-ESP8266NetworkSetup',
      '/posts/250726-ESP8266NetworkSetup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/251013-ESP8266DormitorySmartDoor': RouteRecordInfo<
      '/posts/251013-ESP8266DormitorySmartDoor',
      '/posts/251013-ESP8266DormitorySmartDoor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/251109-MyStage': RouteRecordInfo<
      '/posts/251109-MyStage',
      '/posts/251109-MyStage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/251118-3c3u-config': RouteRecordInfo<
      '/posts/251118-3c3u-config',
      '/posts/251118-3c3u-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/251207-ESP8266AC-IR-Control': RouteRecordInfo<
      '/posts/251207-ESP8266AC-IR-Control',
      '/posts/251207-ESP8266AC-IR-Control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/260124-3c3u-config': RouteRecordInfo<
      '/posts/260124-3c3u-config',
      '/posts/260124-3c3u-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/260319-blog': RouteRecordInfo<
      '/posts/260319-blog',
      '/posts/260319-blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/260408-blog-msg': RouteRecordInfo<
      '/posts/260408-blog-msg',
      '/posts/260408-blog-msg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_f169e6ae657e3474eef0a0161700ebae/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.11_@babel+parse_471cbb1364d4ab9c4f68fe2163949ddd/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_f169e6ae657e3474eef0a0161700ebae/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_f169e6ae657e3474eef0a0161700ebae/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/250725-SmallStationLaunched.md': {
      routes:
        | '/posts/250725-SmallStationLaunched'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/250726-ESP8266NetworkSetup.md': {
      routes:
        | '/posts/250726-ESP8266NetworkSetup'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/251013-ESP8266DormitorySmartDoor.md': {
      routes:
        | '/posts/251013-ESP8266DormitorySmartDoor'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/251109-MyStage.md': {
      routes:
        | '/posts/251109-MyStage'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/251118-3c3u-config.md': {
      routes:
        | '/posts/251118-3c3u-config'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/251207-ESP8266AC-IR-Control.md': {
      routes:
        | '/posts/251207-ESP8266AC-IR-Control'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/260124-3c3u-config.md': {
      routes:
        | '/posts/260124-3c3u-config'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/260319-blog.md': {
      routes:
        | '/posts/260319-blog'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/260408-blog-msg.md': {
      routes:
        | '/posts/260408-blog-msg'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
